import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand cyan override — all cyan-* classes now use #008cb3 palette
        cyan: {
          50:  "#e6f6fb",
          100: "#b3e3f3",
          200: "#80d0eb",
          300: "#4dbde3",
          400: "#26aadb",   // lighter (text, hover states)
          500: "#008cb3",   // ← PRIMARY brand colour
          600: "#007a9e",   // darker active/pressed
          700: "#006789",
          800: "#005574",
          900: "#003d52",
          950: "#002233",
        },
        "on-tertiary": "#135a72",
        "surface-dim": "#031018",
        secondary: "#bce1ff",
        "on-background": "#dfedf9",
        "inverse-on-surface": "#4a5760",
        background: "#031018",
        "primary-fixed": "#72ddfd",
        "on-error": "#490006",
        "inverse-primary": "#00687e",
        "on-tertiary-fixed": "#003d50",
        outline: "#6a7782",
        "tertiary-fixed-dim": "#95d2ee",
        "on-primary-fixed": "#003844",
        "on-surface-variant": "#9fadb8",
        "tertiary-container": "#a3e0fc",
        "on-surface": "#dfedf9",
        "surface-variant": "#152834",
        "surface-container-highest": "#152834",
        "primary-container": "#3aadcc",
        "error-dim": "#d7383b",
        "surface-tint": "#72ddfd",
        "primary-fixed-dim": "#63cfee",
        "on-secondary": "#2d526b",
        error: "#ff716c",
        "on-error-container": "#ffa8a3",
        "on-tertiary-container": "#005169",
        "surface-bright": "#1a2e3b",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed": "#183f57",
        "on-secondary-fixed-variant": "#375c75",
        "on-primary-fixed-variant": "#005669",
        "secondary-fixed-dim": "#aed3f1",
        "tertiary-dim": "#95d2ee",
        "on-primary-container": "#002730",
        "primary-dim": "#63cfee",
        "surface-container-high": "#10212c",
        surface: "#031018",
        "outline-variant": "#3d4a53",
        primary: "#72ddfd",
        "surface-container": "#0b1b25",
        "secondary-fixed": "#bce1ff",
        "inverse-surface": "#f6faff",
        "tertiary-fixed": "#a3e0fc",
        "error-container": "#9f0519",
        "surface-container-low": "#06151e",
        "secondary-container": "#254a63",
        tertiary: "#c4ebff",
        "secondary-dim": "#aed3f1",
        "on-secondary-container": "#b0d5f2",
        "on-tertiary-fixed-variant": "#145b73",
        "on-primary": "#004d5d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      animation: {
        "spin-slow": "spin 10s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
