"use client";

import { useState, useEffect, useRef } from "react";
import type { CustomerBalanceRecord } from "@/app/api/customer-balance/route";

interface BalanceReminderModalProps {
  isOpen: boolean;
  onClose: () => void;
  record: CustomerBalanceRecord | null;
  upiId?: string;
  onBalanceUpdated?: () => void;
}

function playSuccessChime() {
  try {
    const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
    if (!AudioCtx) return;
    const ctx = new AudioCtx();
    const now = ctx.currentTime;
    const osc1 = ctx.createOscillator();
    const gain1 = ctx.createGain();
    osc1.frequency.setValueAtTime(659.25, now);
    gain1.gain.setValueAtTime(0.18, now);
    gain1.gain.exponentialRampToValueAtTime(0.001, now + 0.3);
    osc1.connect(gain1);
    gain1.connect(ctx.destination);
    osc1.start(now);
    osc1.stop(now + 0.3);

    const osc2 = ctx.createOscillator();
    const gain2 = ctx.createGain();
    osc2.frequency.setValueAtTime(987.77, now + 0.15);
    gain2.gain.setValueAtTime(0.2, now + 0.15);
    gain2.gain.exponentialRampToValueAtTime(0.001, now + 0.6);
    osc2.connect(gain2);
    gain2.connect(ctx.destination);
    osc2.start(now + 0.15);
    osc2.stop(now + 0.6);
  } catch (_) {}
}

function formatSafeDate(dateStr?: string | null): string {
  if (!dateStr) return new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  const d = new Date(dateStr);
  if (!isNaN(d.getTime())) {
    return d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  }
  const match = dateStr.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (match) {
    const [, y, m, day] = match;
    const fallback = new Date(parseInt(y), parseInt(m) - 1, parseInt(day));
    if (!isNaN(fallback.getTime())) {
      return fallback.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
    }
  }
  return dateStr;
}

export default function BalanceReminderModal({
  isOpen,
  onClose,
  record,
  onBalanceUpdated,
}: BalanceReminderModalProps) {
  // Tabs: "remind" (WhatsApp link) | "settle" (Cash / Waiver)
  const [activeTab, setActiveTab] = useState<"remind" | "settle">("remind");

  // Razorpay Payment Link State
  const [paymentLink, setPaymentLink] = useState<string>("");
  const [paymentLinkId, setPaymentLinkId] = useState<string>("");
  const [generatingLink, setGeneratingLink] = useState(false);
  const [checkingStatus, setCheckingStatus] = useState(false);
  const [expiringLink, setExpiringLink] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);
  const [msgCopied, setMsgCopied] = useState(false);
  const [rzpPaid, setRzpPaid] = useState(false);
  const [rzpStatus, setRzpStatus] = useState<string>("pending");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Settlement Form State
  const [paymentAmount, setPaymentAmount] = useState<string>("");
  const [paymentMode, setPaymentMode] = useState<string>("Cash at Counter");
  const [settlementNote, setSettlementNote] = useState<string>("");
  const [settling, setSettling] = useState(false);

  // Auto-generation tracker
  const autoGeneratedForRef = useRef<string | null>(null);

  // Reset and load / auto-generate link when record changes
  useEffect(() => {
    if (record && isOpen) {
      setPaymentAmount((record.balance_amount ?? 0).toString());
      setSettlementNote("");
      setRzpPaid(record.status === "settled");
      setErrorMessage(null);
      setActiveTab("remind");

      if (record.razorpay_payment_link_url) {
        setPaymentLink(record.razorpay_payment_link_url);
        setPaymentLinkId(record.razorpay_payment_link_id || "");
        setRzpStatus("created");
      } else if (record.balance_amount > 0 && autoGeneratedForRef.current !== record.id) {
        autoGeneratedForRef.current = record.id;
        handleGeneratePaymentLink(record);
      }
    }
  }, [record, isOpen]);

  // Poll Razorpay Payment Link status while modal is open (HOOK MUST REMAIN UNCONDITIONAL AT COMPONENT ROOT)
  useEffect(() => {
    if (!isOpen || !record || !paymentLinkId || rzpPaid || record.balance_amount <= 0) return;

    const interval = setInterval(async () => {
      try {
        const res = await fetch(`/api/razorpay/payment-link?link_id=${encodeURIComponent(paymentLinkId)}`);
        const data = await res.json();
        if (data?.success) {
          if (data.paid || data.status === "paid") {
            setRzpPaid(true);
            setRzpStatus("paid");
            playSuccessChime();
            clearInterval(interval);

            // Record settled in API
            await fetch("/api/customer-balance", {
              method: "PATCH",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                id: record.id,
                action: "RECORD_PAYMENT",
                amountReceived: record.balance_amount,
                paymentMethod: "Razorpay Link (Verified)",
                settlementNote: `Paid in full via Razorpay Payment Link (${data.payment?.id || paymentLinkId})`,
              }),
            });

            if (onBalanceUpdated) onBalanceUpdated();
          } else if (data.status) {
            setRzpStatus(data.status);
          }
        }
      } catch (_) {}
    }, 4000);

    return () => clearInterval(interval);
  }, [isOpen, record?.id, record?.balance_amount, paymentLinkId, rzpPaid, onBalanceUpdated]);

  // 1. Generate Razorpay Payment Link
  const handleGeneratePaymentLink = async (currentRecord?: CustomerBalanceRecord | null) => {
    const rec = currentRecord || record;
    if (!rec || rec.balance_amount <= 0) return null;

    setGeneratingLink(true);
    setErrorMessage(null);
    try {
      const cleanPhone = (rec.customer_phone || "").replace(/\D/g, "").slice(-10);
      const res = await fetch("/api/razorpay/payment-link", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          amount: rec.balance_amount,
          customerName: rec.customer_name,
          customerPhone: cleanPhone,
          orderRef: `BAL-${rec.invoice_id}`,
          itemsSummary: `Remaining Balance for Inv #${rec.invoice_id}`,
          notes: `Remaining balance for ${rec.customer_name} (#${rec.invoice_id})`,
        }),
      });
      const data = await res.json();
      if (data?.success && data.paymentLink?.short_url) {
        const linkUrl = data.paymentLink.short_url;
        const linkId = data.paymentLink.id;
        setPaymentLink(linkUrl);
        setPaymentLinkId(linkId);
        setRzpStatus("created");

        // Sync to API
        await fetch("/api/customer-balance", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            id: rec.id,
            action: "UPDATE_LINKS",
            razorpayPaymentLinkId: linkId,
            razorpayPaymentLinkUrl: linkUrl,
          }),
        });

        if (onBalanceUpdated) onBalanceUpdated();
        return linkUrl;
      } else {
        setErrorMessage(data?.error || "Failed to generate Razorpay Payment Link");
      }
    } catch (err: any) {
      setErrorMessage(err?.message || "Failed to generate Razorpay Payment Link");
    } finally {
      setGeneratingLink(false);
    }
    return null;
  };

  // Early return strictly AFTER all hooks have executed
  if (!isOpen || !record) return null;

  const cleanPhone = (record.customer_phone || "").replace(/\D/g, "").slice(-10);

  // Generate polite automated WhatsApp message
  const generateWhatsAppMessage = (directPayLink?: string) => {
    const link = directPayLink || paymentLink;
    const paySection = link
      ? `\n💳 *Clear Balance Online (Instant UPI / Cards / NetBanking):*\n👉 ${link}`
      : `\n💳 *Clear Balance Online (Generating Secure Link...)*`;

    return `*AUTOMATED ACCOUNT STATEMENT / PAYMENT UPDATE*
_Urban Trout Aquaculture · Srinagar, Kashmir_

Dear *${record.customer_name}*,

This is an automated system-generated billing update regarding your recent order with Urban Trout.

📄 *Statement Details:*
• *Order / Invoice Ref:* #${record.invoice_id}
• *Date:* ${formatSafeDate(record.created_at)}
• *Order Items:* ${record.items_summary || "Fresh Rainbow Trout"}

💰 *Payment Breakdown:*
• *Total Bill Amount:* Rs. ${(Number(record.total_amount) || 0).toLocaleString("en-IN")}
• *Amount Received:* Rs. ${(Number(record.paid_amount) || 0).toLocaleString("en-IN")}
• *Outstanding Balance Due:* *Rs. ${(Number(record.balance_amount) || 0).toLocaleString("en-IN")}*
${paySection}

━━━━━━━━━━━━━━━━━━━━
_ℹ️ Automated Notice: This is a system-generated statement. This secure Razorpay link is locked for this invoice reference and automatically expires upon payment. If you have already cleared this payment in cash or via recent transfer, please disregard this message or reply to this chat so our team can update your ledger._

Warm regards,
*Urban Trout Aquaculture, Srinagar*
Helpline: +91 84910 06127`;
  };

  // 2. Open WhatsApp with prefilled polite system reminder
  const handleSendWhatsApp = async () => {
    let currentLink = paymentLink;
    if (!currentLink && record.balance_amount > 0) {
      currentLink = (await handleGeneratePaymentLink()) || "";
    }

    const message = generateWhatsAppMessage(currentLink);
    const encoded = encodeURIComponent(message);
    const url = cleanPhone.length === 10
      ? `https://wa.me/91${cleanPhone}?text=${encoded}`
      : `https://wa.me/?text=${encoded}`;

    window.open(url, "_blank");

    // Mark reminder timestamp in API
    try {
      await fetch("/api/customer-balance", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: record.id,
          action: "REMINDER_SENT",
          razorpayPaymentLinkId: paymentLinkId,
          razorpayPaymentLinkUrl: currentLink,
        }),
      });
      if (onBalanceUpdated) onBalanceUpdated();
    } catch (_) {}
  };

  // 3. Manually check status now (like in WhatsApp ordering system)
  const handleCheckStatusNow = async () => {
    if (!paymentLinkId) return;
    setCheckingStatus(true);
    setErrorMessage(null);
    try {
      const res = await fetch(`/api/razorpay/payment-link?link_id=${encodeURIComponent(paymentLinkId)}`);
      const data = await res.json();
      if (!data?.success) {
        setErrorMessage(data?.error || "Status check failed");
        return;
      }

      if (data.paid || data.status === "paid") {
        setRzpPaid(true);
        setRzpStatus("paid");
        playSuccessChime();

        await fetch("/api/customer-balance", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            id: record.id,
            action: "RECORD_PAYMENT",
            amountReceived: record.balance_amount,
            paymentMethod: "Razorpay Link (Verified)",
            settlementNote: `Paid in full via Razorpay Payment Link (${data.payment?.id || paymentLinkId})`,
          }),
        });

        if (onBalanceUpdated) onBalanceUpdated();
        alert(`🎉 Payment Confirmed! ₹${(Number(record.balance_amount) || 0).toLocaleString("en-IN")} received from ${record.customer_name}. Ledger auto-updated.`);
      } else {
        setRzpStatus(data.status || "created");
        alert(`⏳ Customer has NOT paid yet (Razorpay link status: "${data.status || "pending"}").`);
      }
    } catch (e: any) {
      setErrorMessage(e?.message || "Could not check status");
    } finally {
      setCheckingStatus(false);
    }
  };

  // 4. Expire / Cancel link on Razorpay so customer cannot pay twice
  const handleExpirePaymentLink = async () => {
    if (!paymentLinkId) return;
    if (!window.confirm(`Cancel & Expire Razorpay link (${paymentLinkId}) so the customer cannot pay it online?`)) {
      return;
    }

    setExpiringLink(true);
    try {
      await fetch(`/api/razorpay/payment-link?link_id=${encodeURIComponent(paymentLinkId)}`, {
        method: "DELETE",
      });

      // Clear from record in DB
      await fetch("/api/customer-balance", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: record.id,
          action: "CANCEL_LINK",
        }),
      });

      setPaymentLink("");
      setPaymentLinkId("");
      setRzpStatus("cancelled");
      if (onBalanceUpdated) onBalanceUpdated();
      alert("Payment link has been cancelled and expired on Razorpay.");
    } catch (e: any) {
      alert("Failed to cancel link: " + (e?.message || "Unknown error"));
    } finally {
      setExpiringLink(false);
    }
  };

  // 5. Record Cash Payment at Counter
  const handleRecordRepayment = async () => {
    const amount = Number(paymentAmount);
    if (isNaN(amount) || amount <= 0) {
      alert("Please enter a valid amount greater than ₹0");
      return;
    }

    setSettling(true);
    try {
      const res = await fetch("/api/customer-balance", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: record.id,
          action: "RECORD_PAYMENT",
          amountReceived: amount,
          paymentMethod: paymentMode,
          settlementNote: settlementNote.trim() || `Received ₹${amount} via ${paymentMode}`,
        }),
      });

      const data = await res.json();
      if (data?.success) {
        // If paid in full, expire the online payment link so customer cannot pay online too
        if (amount >= record.balance_amount && paymentLinkId) {
          try {
            await fetch(`/api/razorpay/payment-link?link_id=${encodeURIComponent(paymentLinkId)}`, {
              method: "DELETE",
            });
          } catch (_) {}
        }

        if (onBalanceUpdated) onBalanceUpdated();
        onClose();
      } else {
        alert(data?.error || "Failed to record payment");
      }
    } catch (e: any) {
      alert(e?.message || "Failed to record payment");
    } finally {
      setSettling(false);
    }
  };

  // 6. Settle as Final Waiver / Concession
  const handleSettleFinalWaiver = async () => {
    const reason = window.prompt(
      `Mark remaining balance of ₹${record.balance_amount} as settled/waived? Enter settlement reason:`,
      "Agreed final settlement / courtesy discount"
    );

    if (reason === null) return;

    setSettling(true);
    try {
      const res = await fetch("/api/customer-balance", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: record.id,
          action: "SETTLE_FINAL_WAIVER",
          settlementNote: reason.trim() || "Agreed settlement as final payment",
        }),
      });

      const data = await res.json();
      if (data?.success) {
        // Expire active payment link on Razorpay
        if (paymentLinkId) {
          try {
            await fetch(`/api/razorpay/payment-link?link_id=${encodeURIComponent(paymentLinkId)}`, {
              method: "DELETE",
            });
          } catch (_) {}
        }

        if (onBalanceUpdated) onBalanceUpdated();
        onClose();
      } else {
        alert(data?.error || "Failed to settle balance");
      }
    } catch (e: any) {
      alert(e?.message || "Failed to settle balance");
    } finally {
      setSettling(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md animate-fadeIn">
      <div className="bg-slate-900 border border-slate-700/80 rounded-2xl w-full max-w-xl overflow-hidden shadow-2xl flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-cyan-500/20 border border-cyan-500/40 text-cyan-400 flex items-center justify-center font-bold text-lg">
              <span className="material-symbols-outlined text-lg">link</span>
            </div>
            <div>
              <h3 className="font-bold text-white text-base" style={{ fontFamily: '"Space Grotesk", sans-serif' }}>
                Razorpay Payment Link &amp; Balance Reminder
              </h3>
              <p className="text-slate-400 text-xs font-mono">
                Invoice #{record.invoice_id} · {record.customer_name}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white flex items-center justify-center transition-colors text-sm"
          >
            ✕
          </button>
        </div>

        {/* Balance Overview Card */}
        <div className="p-4 bg-gradient-to-r from-cyan-950/30 via-slate-900 to-amber-950/20 border-b border-slate-800">
          <div className="grid grid-cols-3 gap-2 text-center">
            <div className="bg-slate-950/60 p-2.5 rounded-xl border border-slate-800">
              <p className="text-[10px] uppercase tracking-wider text-slate-400 font-bold">Total Bill</p>
              <p className="text-sm font-bold text-white font-mono mt-0.5">₹{(Number(record.total_amount) || 0).toLocaleString("en-IN")}</p>
            </div>
            <div className="bg-slate-950/60 p-2.5 rounded-xl border border-emerald-500/20">
              <p className="text-[10px] uppercase tracking-wider text-emerald-400 font-bold">Paid So Far</p>
              <p className="text-sm font-bold text-emerald-300 font-mono mt-0.5">₹{(Number(record.paid_amount) || 0).toLocaleString("en-IN")}</p>
            </div>
            <div className="bg-slate-950/80 p-2.5 rounded-xl border border-cyan-500/40 shadow-inner">
              <p className="text-[10px] uppercase tracking-wider text-cyan-400 font-bold">Remaining Balance</p>
              <p className="text-base font-extrabold text-cyan-300 font-mono mt-0.5">₹{(Number(record.balance_amount) || 0).toLocaleString("en-IN")}</p>
            </div>
          </div>

          <div className="flex items-center justify-between text-xs text-slate-400 mt-3 pt-2 border-t border-slate-800/60">
            <div className="flex items-center gap-1.5">
              <span className="material-symbols-outlined text-sm text-cyan-400">phone</span>
              <span className="font-mono text-slate-200">{cleanPhone ? `+91 ${cleanPhone}` : "No Phone"}</span>
            </div>
            <div>
              Status:{" "}
              <span
                className={`font-bold px-2 py-0.5 rounded text-[10px] uppercase ${
                  record.status === "settled" || rzpPaid
                    ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                    : record.status === "waived_final"
                    ? "bg-blue-500/20 text-blue-300 border border-blue-500/40"
                    : "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                }`}
              >
                {rzpPaid ? "PAID ✓" : record.status === "waived_final" ? "Waived Final" : record.status}
              </span>
            </div>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex border-b border-slate-800 bg-slate-950/50 text-xs font-semibold">
          <button
            type="button"
            onClick={() => setActiveTab("remind")}
            className={`flex-1 py-2.5 px-3 flex items-center justify-center gap-1.5 border-b-2 transition-all cursor-pointer ${
              activeTab === "remind"
                ? "border-cyan-400 text-cyan-300 bg-cyan-500/10"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <span className="material-symbols-outlined text-sm">chat</span>
            WhatsApp Razorpay Link
          </button>

          <button
            type="button"
            onClick={() => setActiveTab("settle")}
            className={`flex-1 py-2.5 px-3 flex items-center justify-center gap-1.5 border-b-2 transition-all cursor-pointer ${
              activeTab === "settle"
                ? "border-amber-400 text-amber-300 bg-amber-500/10"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <span className="material-symbols-outlined text-sm">payments</span>
            Cash Settlement &amp; Waiver
          </button>
        </div>

        {/* Tab Body */}
        <div className="p-4 overflow-y-auto flex-1 space-y-4">
          {/* TAB 1: WHATSAPP PAYMENT LINK */}
          {activeTab === "remind" && (
            <div className="space-y-3">
              {/* Paid Banner */}
              {rzpPaid ? (
                <div className="p-4 bg-emerald-950/40 border border-emerald-500/50 rounded-2xl text-center space-y-1.5">
                  <div className="w-10 h-10 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto text-xl font-bold">
                    ✓
                  </div>
                  <h4 className="text-base font-bold text-white">Payment Received!</h4>
                  <p className="text-xs text-emerald-300">
                    Remaining balance of ₹{(Number(record.balance_amount) || 0).toLocaleString("en-IN")} cleared via Razorpay Payment Link. Auto-logged to Vending Log.
                  </p>
                </div>
              ) : (
                /* Active Razorpay Link Card */
                <div className="p-3.5 bg-slate-950/90 border border-cyan-500/30 rounded-xl space-y-2.5">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-cyan-400 animate-ping" />
                      <span className="text-[11px] uppercase tracking-wider font-bold text-cyan-300">
                        Official Razorpay Payment Link
                      </span>
                    </div>
                    {paymentLinkId && (
                      <span className="text-[10px] font-mono text-slate-400 bg-slate-900 border border-slate-700/80 px-2 py-0.5 rounded">
                        {paymentLinkId}
                      </span>
                    )}
                  </div>

                  {generatingLink ? (
                    <div className="p-3 bg-slate-900 rounded-lg flex items-center justify-center gap-2 text-cyan-300 text-xs font-mono">
                      <div className="w-4 h-4 border-2 border-cyan-400 border-t-transparent rounded-full animate-spin" />
                      Generating single-use Razorpay Link...
                    </div>
                  ) : paymentLink ? (
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 p-2 bg-slate-900 border border-slate-800 rounded-lg">
                        <span className="material-symbols-outlined text-sm text-cyan-400">link</span>
                        <input
                          type="text"
                          readOnly
                          value={paymentLink}
                          className="w-full bg-transparent text-cyan-300 font-mono text-xs focus:outline-none select-all"
                        />
                        <button
                          type="button"
                          onClick={() => {
                            navigator.clipboard.writeText(paymentLink);
                            setLinkCopied(true);
                            setTimeout(() => setLinkCopied(false), 2000);
                          }}
                          className="px-2 py-1 rounded bg-cyan-600/30 hover:bg-cyan-600/50 text-cyan-200 text-[10.5px] font-bold shrink-0 transition-colors cursor-pointer"
                        >
                          {linkCopied ? "✓ Copied" : "Copy"}
                        </button>
                      </div>

                      {/* Link Actions Row */}
                      <div className="flex items-center justify-between gap-1.5 pt-1">
                        <button
                          type="button"
                          onClick={handleCheckStatusNow}
                          disabled={checkingStatus}
                          className="flex-1 py-1.5 px-2.5 rounded-lg bg-cyan-600/20 hover:bg-cyan-600/30 text-cyan-300 border border-cyan-500/40 text-[11px] font-bold font-mono flex items-center justify-center gap-1.5 transition-all cursor-pointer disabled:opacity-50"
                          title="Poll Razorpay status directly"
                        >
                          <span className={`material-symbols-outlined text-xs ${checkingStatus ? "animate-spin" : ""}`}>
                            sync
                          </span>
                          {checkingStatus ? "Checking..." : "Check Status Now"}
                        </button>

                        <a
                          href={paymentLink}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="py-1.5 px-3 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-[11px] font-bold font-mono flex items-center justify-center gap-1 transition-all"
                        >
                          <span className="material-symbols-outlined text-xs">open_in_new</span>
                          Open
                        </a>

                        <button
                          type="button"
                          onClick={handleExpirePaymentLink}
                          disabled={expiringLink}
                          className="py-1.5 px-2.5 rounded-lg bg-rose-950/40 hover:bg-rose-900/60 text-rose-300 border border-rose-500/40 text-[11px] font-bold font-mono flex items-center justify-center gap-1 transition-all cursor-pointer disabled:opacity-50"
                          title="Cancel and expire this link on Razorpay"
                        >
                          <span className="material-symbols-outlined text-xs">delete_forever</span>
                          {expiringLink ? "..." : "Expire Link"}
                        </button>
                      </div>

                      <div className="flex items-center justify-between text-[10.5px] text-slate-400 font-mono pt-0.5">
                        <span className="flex items-center gap-1 text-emerald-400">
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                          Live auto-monitoring payment status
                        </span>
                        <span>Locked: ₹{(Number(record.balance_amount) || 0).toLocaleString("en-IN")}</span>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-2">
                      <button
                        type="button"
                        onClick={() => handleGeneratePaymentLink()}
                        className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white font-bold text-xs shadow-lg transition-all"
                      >
                        Generate Razorpay Payment Link
                      </button>
                    </div>
                  )}

                  {errorMessage && <p className="text-xs text-rose-400 font-mono">{errorMessage}</p>}
                </div>
              )}

              {/* Message Preview Box */}
              <div className="bg-slate-950 border border-slate-800 rounded-xl p-3 text-slate-300 text-xs font-mono whitespace-pre-wrap leading-relaxed max-h-52 overflow-y-auto">
                {generateWhatsAppMessage()}
              </div>

              {/* Send Buttons */}
              <div className="flex flex-wrap items-center gap-2 pt-1">
                <button
                  type="button"
                  onClick={handleSendWhatsApp}
                  disabled={!cleanPhone || generatingLink}
                  className="flex-1 py-2.5 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/30 transition-all cursor-pointer"
                >
                  <span className="material-symbols-outlined text-sm">send</span>
                  Send on WhatsApp (+91 {cleanPhone || "N/A"})
                </button>

                <button
                  type="button"
                  onClick={() => {
                    navigator.clipboard.writeText(generateWhatsAppMessage());
                    setMsgCopied(true);
                    setTimeout(() => setMsgCopied(false), 2000);
                  }}
                  className="py-2.5 px-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold transition-all cursor-pointer"
                >
                  {msgCopied ? "✓ Copied" : "Copy Message"}
                </button>
              </div>

              {record.last_reminder_sent_at && (
                <p className="text-center text-[11px] text-slate-400 font-mono">
                  Last reminder sent: {formatSafeDate(record.last_reminder_sent_at)}
                </p>
              )}
            </div>
          )}

          {/* TAB 2: CASH SETTLEMENT & WAIVER */}
          {activeTab === "settle" && (
            <div className="space-y-4">
              {/* Option 1: Record Cash Repayment */}
              <div className="p-3.5 bg-slate-950 border border-slate-800 rounded-xl space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold text-white uppercase tracking-wider">
                    Record Counter Cash Payment
                  </h4>
                  <span className="text-[11px] text-amber-400 font-mono font-bold">
                    Balance: ₹{(Number(record.balance_amount) || 0).toLocaleString("en-IN")}
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="text-[10px] text-slate-400 font-bold block mb-1">Amount Received (₹)</label>
                    <input
                      type="number"
                      value={paymentAmount}
                      onChange={(e) => setPaymentAmount(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white font-mono text-sm focus:border-amber-400 focus:outline-none"
                      placeholder="e.g. 500"
                    />
                  </div>
                  <div>
                    <label className="text-[10px] text-slate-400 font-bold block mb-1">Payment Method</label>
                    <select
                      value={paymentMode}
                      onChange={(e) => setPaymentMode(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white text-xs focus:border-amber-400 focus:outline-none"
                    >
                      <option value="Cash at Counter">Cash at Counter</option>
                      <option value="Online Bank Transfer">Online Bank Transfer</option>
                      <option value="Direct Razorpay Link">Direct Razorpay Link</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="text-[10px] text-slate-400 font-bold block mb-1">Note (Optional)</label>
                  <input
                    type="text"
                    value={settlementNote}
                    onChange={(e) => setSettlementNote(e.target.value)}
                    placeholder="e.g. Handed over cash at shop"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-white text-xs focus:border-amber-400 focus:outline-none"
                  />
                </div>

                <button
                  type="button"
                  onClick={handleRecordRepayment}
                  disabled={settling}
                  className="w-full py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-slate-950 font-bold text-xs shadow-lg shadow-amber-950/40 transition-all cursor-pointer"
                >
                  {settling ? "Recording..." : `Record ₹${paymentAmount || 0} Cash Payment`}
                </button>
              </div>

              {/* Option 2: Settle as Final Amount / Discount Waiver */}
              <div className="p-3.5 bg-blue-950/20 border border-blue-500/30 rounded-xl space-y-2">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-blue-400 text-base">handshake</span>
                  <h4 className="text-xs font-bold text-blue-300">
                    Settle as Final Payment (Discount Waiver)
                  </h4>
                </div>
                <p className="text-[11px] text-slate-300 leading-relaxed">
                  If the customer paid partial cash and both agreed that it was the final amount, mark it settled here. This zeroes the balance and cancels any pending Razorpay link so the customer cannot pay again.
                </p>

                <button
                  type="button"
                  onClick={handleSettleFinalWaiver}
                  disabled={settling}
                  className="w-full py-2 px-3 rounded-lg bg-blue-600/30 hover:bg-blue-600/50 border border-blue-500/40 text-blue-200 text-xs font-bold transition-all cursor-pointer"
                >
                  Mark as Agreed Final Payment (Zero Balance)
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-3 bg-slate-950 border-t border-slate-800 flex items-center justify-between text-xs">
          <span className="text-slate-500 font-mono text-[11px]">Urban Trout · Razorpay Khata</span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold text-xs"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
